### ISSUE TITLE
MavenCenter

### ISSUE THREAD

**Issue by gorbuvla** [AckeeCZ/ackroutine-adapter#31]
Whats up, any plans on moving to mavenCentral? 🙂

**Comment by davidbilik** [comment]
hush

**Comment by gorbuvla** [comment]
hey, still no progress here? or do you plan on moving at all?

**Comment by davidbilik** [comment]
Hey, is it somehow blocking you? 😀 Until no new features are added there is no reason to migrate. We are also thinking of a new name for the library so we will do the migration with rebranding

**Comment by gorbuvla** [comment]
not really, lint annoys me so i decided to annoy you
